"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './about/profile/navbar'
import { useState } from 'react'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })
const DisableNavbar = ['/login', '/register']

// export const metadata: Metadata = {
//   title: 'Belajar appRouter',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [state, setState] = useState(0);
  const pathname = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
        {!DisableNavbar.includes(pathname) && <Navbar/>}
        
        {/* <h1>hello word{state}</h1> */}
        {/* <button onClick={() => setState(state + 1)}>button</button> */}
        </>
        {children}</body>
    </html>
  )
}
